version: '3'

services:
  ui:
    build:
      dockerfile: Dockerfile
      context: ui
    depends_on:
      - server
    environment:
      SERVER_URL: "http://server:8080"
      SERVER_HOST: "server"
      SERVER_PORT: "8080"
    ports:
      - "3000:80"

  server:
    build:
      dockerfile: Dockerfile
      context: server
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "invites"
      DB_NAME: "invites"
      SEED: "true"

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "invites"
      MYSQL_DATABASE: "invites"
    ports:
      - "3306:3306"